apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: dev-

namespace: syed-dev

resources:
- ../../base
- namespace.yaml
- ingress.yaml

patches:
  - target:
      kind: Deployment
      name: sre-app
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
